### ISSUE TITLE
Broken as of Textractor 4.9.1

### ISSUE THREAD

**Issue by koma-cute** [2yu3/Textractor-BrowserExtension#1]
Attempting to load the extension in 4.9.1 crashes Textractor. 4.9.0 is seemingly fine. I looked at the [https://github.com/Artikash/Textractor/compare/v4.9.0...v4.9.1](diff) between the two, and the only real related, non cosmetic change I can see is the addition of codesigning. I tried removing the signatures from the files in 4.9.1 but it didn't make a difference, so I'm not sure what the real problem is.

Output from event viewer after crashing (0xc0000409/buffer overrun):

```
Faulting application name: Textractor.exe, version: 0.0.0.0, time stamp: 0x5ebde7e4
Faulting module name: Qt5Core.dll, version: 5.13.2.0, time stamp: 0x5db2a9fc
Exception code: 0xc0000409
Fault offset: 0x0001dec1
Faulting process ID: 0x1ec0
Faulting application start time: 0x01d6482bb34c9a40
Faulting application path: C:\Program Files (x86)\Textractor\x86\Textractor.exe
Faulting module path: C:\Program Files (x86)\Textractor\x86\Qt5Core.dll
Report ID: 73d9fad7-363b-4388-8673-5a322e275480
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by TomBPotochek** [comment]
I just stumbled upon this extension and was immediately bummed that it did not work, as you mentioned. However, I tried compiling the extension and Textractor from source and it works. I have tried only compiling Textractor and using the precompiled .dll files from this extension's releases and that doesn't work. However, I haven't tried to just compile the extension and use the signed binaries of Textractor, but right now I can certify that you can get it to work by compiling everything.

**Comment by koma-cute** [comment]
I'm not sure the reason, but the last time I used Textractor (version 4.15.0) I didn't have any issues, even with the precompiled version from this repo, so I don't think you even have to do that yourself anymore either.

**Comment by TomBPotochek** [comment]
The latest version of textractor (4.16.1) yielded a "invalid extension" message when adding the precompiled binaries of this extension, so I assumed that was what you were talking about. I even made sure to use x86 versions for the x86 version of textractor and such. Weird then.
